trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  GO_VERSION: "1.25.4"
  OUTPUT_NAME: "komercio-api"
  DEPLOY_PATH: "/home/azureuser/komercio/app"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: GoTool@0
            inputs:
              version: "$(GO_VERSION)"

          - script: |
              echo "Compilando..."
              cd cmd
              go build -o komercio-api main.go

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "cmd/komercio-api"
              artifact: "drop"

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployJob
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: "drop"
              targetPath: "$(Pipeline.Workspace)/drop"

          # PARAR SERVIÇO ANTES DE COPIAR
          - task: SSH@0
            displayName: "Parar serviço (desbloquear binário)"
            inputs:
              sshEndpoint: "Komercio-API-VM"
              runOptions: inline
              inline: |
                sudo systemctl stop komercio || true
                sleep 1

          # AGORA SIM COPIA O BINÁRIO
          - task: CopyFilesOverSSH@0
            displayName: "Copiar binário para VM"
            inputs:
              sshEndpoint: "Komercio-API-VM"
              sourceFolder: "$(Pipeline.Workspace)/drop"
              contents: "komercio-api"
              targetFolder: "/home/azureuser/komercio/app"
              cleanTargetFolder: false

          # REINICIAR API E VALIDAR
          - task: SSH@0
            displayName: "Reiniciar API e testar"
            inputs:
              sshEndpoint: "Komercio-API-VM"
              runOptions: inline
              inline: |
                sudo chmod +x /home/azureuser/komercio/app/komercio-api
                sudo systemctl start komercio
                sleep 3
